## Describe the fields
## For definition, provide the expected key:values
## Note that several keys/values can be defined

###############################################
## SnpEff Parsing

snpeff:

  ## Tags
  freqTag: 'AF'
  depthTag: 'DP'
  annotTag: 'ANN'

  ## Annotation flags
  isCoding:
    1:
      - intragenic_variant

  isNonCoding:
    1:
      - intergenic_region
      - intron_variant
      - upstream_gene_variant
      - 5_prime_UTR_variant
      - 3_prime_UTR_variant

  isSynonymous:
    1:
      - synonymous_variant
  
  isNonSynonymous:
    1:
      - missense_variant
      - initiator_codon_variant
      - stop_retained_variant
      - stop_gained

  ## Databases
  cancerDb:
    cosmic:
      - cosmic_coding_ID
      - cosmic_noncoding_ID

  genomeDb:
    1k:
      - kg_AMR_AF
      - kg_AFR_AF
      - kg_EAS_AF
      - kg_EUR_AF
      - kg_SAS_AF

    gnomad:
      - gnomAD_genomes_AF


#################################################
## ANNOVAR Parsing

annovar:

  ## Tags
  freqTag: 'ALLELIC_RATIO'
  depthTag: 'DEP'
  annotTag: ''

  ## Annotation flags
  isCoding:
    Func.refGene:
      - exonic
      - splicing

  isNonCoding:
    Func.refGene:  
    - intronic

  isSynonymous:
    ExonicFunc.refGene:
      - synonymous_SNV

  isNonSynonymous:
    ExonicFunc.refGene
      - nonsynonymous_SNV

  ## Databases
  cancerDb:
    cosmic:
      - cosmic86

  genomeDb:
    1k:
      - 1000g2015aug_all

    gnomad:
      - gnomAD_exome_ALL

    exac:
      - ExAC_ALL