## Describe the fields
## For definition, provide the expected key:values
## Note that several keys/values can be defined

snpeff:
  tag: 'ANN'

  isCoding:
    1:
      - intragenic_variant

  isNonCoding:
    1:
      - intergenic_region
      - intron_variant
      - upstream_gene_variant
      - 5_prime_UTR_variant
      - 3_prime_UTR_variant

  isSynonymous:
    1:
      - synonymous_variant
  
  isNonSynonymous:
    1:
      - missense_variant
      - initiator_codon_variant
      - stop_retained_variant
      - stop_gained

  isHotspot:
    cosmic:
      - cosmic_coding_ID
      - cosmic_noncoding_ID

  isGermline:
    1K:
    gnomAD:

annovar:
  tag: ''

  isCoding:
    Func.refGene:
      - exonic
      - splicing

  isNonCoding:
    Func.refGene:  
    - intronic

  isSynonymous:
    ExonicFunc.refGene:
      - synonymous_SNV
    TYPE:
      - synonymous_SNV

  isNonSynonymous:
    - ExonicFunc.refGene=nonsynonymous_SNV

  isHotspot:

  isGermline: